name: Pull request checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

jobs:
  pull-request-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./paaster

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: npm install
      - name: Check linting
        run: npm run check
      - name: Attempt to build codebase
        run: npm run build
